name: sonic-lool
version: 2017-01+git
summary: Software for Open Networking in the Cloud (SONiC)
description: |
  SONiC is an open source project for network routers and switches.
grade: devel
confinement: devmode

apps:
  redis-server:
    command: redis-launcher
    daemon: simple
  redis-cli:
    command: redis-cli-launcher
  syncd:
    command: syncd-launcher
    daemon: simple
  # missing from swss: fpmsyncd, intfsyncd, neighsyncd, orchagent, portsyncd,
  # teamsyncd; also swssconfig

hooks:
  configure:
    plugs: []

parts:
  # redis debs built by SONiC's jenkins; this could be replaced with the
  # upstream git repo or the redis-server deb from Ubuntu
  redis-deb:
    plugin: nil
    build-packages: [httpie, jq, wget]
    stage-packages: [libjemalloc1]
    install: |
      job="common/job/redis-build"
      # TODO this should be a plugin; currently doesn't fail on missing debs
      # and doesn't resolve dependencies
      debs_re="(redis-server|redis-tools)"
      wget `./get-debs "$job" "$debs_re"`
      for d in *.deb; do dpkg -x $d $SNAPCRAFT_PART_INSTALL; done
      # comment out config entries we want to override
      sed -ri -e '/^(daemonize|dir|logfile|port|unixsocket) /s/^/#/' \
          $SNAPCRAFT_PART_INSTALL/etc/redis/redis.conf
      # allows relative path to redis-socket to work (see hack below)
      ln -s /var/snap/sonic-lool/current/run/redis.sock \
          $SNAPCRAFT_PART_INSTALL/link-to-redis-socket.sock
    stage:
      - etc/redis/redis.conf
      - usr/bin/redis-*
      - usr/lib/*/*.so.*
      - link-to-redis-socket.sock

  # common code, wrappers, configure hook etc.
  common:
    plugin: dump
    source: common

  broadcom-backend:
    plugin: nil
    build-packages: [httpie, jq, wget]
    install: |
      job="broadcom/job/buildimage-brcm-all"
      # TODO this should be a plugin; currently doesn't fail on missing debs
      # and doesn't resolve dependencies
      debs_re="(swss|syncd|libswsscommon|libsaibcm|libsaimetadata|libsairedis|libhiredis0\\.13|libnl-3-200|libnl-genl-3-200|libnl-cli-3-200|libnl-route-3-200|libnl-nf-3-200|libteam5|libopennsl)"
      wget `./get-debs "$job" "$debs_re"`
      for d in *.deb; do dpkg -x $d $SNAPCRAFT_PART_INSTALL/broadcom; done
      # missing SONAME symlink is probably coming out of -dev deb instead of lib
      ln -s libsai.so.1.0 $SNAPCRAFT_PART_INSTALL/broadcom/usr/lib/libsai.so.1
      # /var/run/redis/redis.sock is hardcoded in a bunch of binaries with
      # no runtime override (flag or env var) so patch the binaries for now;
      # see github.com/Azure/sonic-swss-common, common/dbconnector.h for
      # definition and github.com/Azure/sonic-sairedis, syncd/syncd.cpp for
      # usage
      # NB: strings are of exact same length and this will be a relative path
      # so working directory will matter
      sed -i 's#/var/run/redis/redis\.sock#link-to-redis-socket.sock#g' \
          $SNAPCRAFT_PART_INSTALL/broadcom/usr/bin/*
    stage:
      - broadcom/lib/*/*.so.*
      - broadcom/usr/lib/*.so.*
      - broadcom/usr/lib/*/*.so.*
      - broadcom/usr/bin/*

